apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
data:
  mysql-server: postgres            # The name of postgres service
  mysql-database-name: tweet        # The name of the database used by app
  mysql-user-username: postgres     # A new created user for the app