services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tweeter
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:latest
    ports:
      - "6379:6379"